language: generic
script:
- bash ./compile.sh
branches:
  only:
  - master
deploy:
  provider: pages
  local_dir: out
  deploy_key: deploy_key
  edge:
    branch: master
notifications:
  email:
    on_success: never
    on_failure: always
before_install:
- openssl aes-256-cbc -K $encrypted_189e52c2c347_key -iv $encrypted_189e52c2c347_iv
  -in deploy_key.enc -out deploy_key -d
